
version: '{branch}.{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCHITECTURE: x64
      BUILD_CRT: VC15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCHITECTURE: x86
      BUILD_CRT: VC15

install:
  - appveyor\install.cmd

build_script:
  - appveyor\build.cmd

artifacts:
  - path: artifacts
    name: mod_authn_ntlm-%APPVEYOR_REPO_TAG_NAME%-%ARCHITECTURE%-%BUILD_CRT%
    type: zip
#  - path: build
#    name: mod_authn_ntlm-%APPVEYOR_REPO_TAG_NAME%-%ARCHITECTURE%-%BUILD_CRT%-Build
#    type: zip
