
version: '{branch}.{build}'

cache:
  - c:\build-cache

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCHITECTURE: x64
      BUILD_CRT: VC15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCHITECTURE: x86
      BUILD_CRT: VC15

install:
  - ps: appveyor\install.ps1

build_script:
  - ps: appveyor\build.ps1

artifacts:
  - path: artifacts
    name: mod_authn_ntlm-%APPVEYOR_REPO_TAG_NAME%-%ARCHITECTURE%-%BUILD_CRT%
    type: zip
#  - path: build
#    name: mod_authn_ntlm-%APPVEYOR_REPO_TAG_NAME%-%ARCHITECTURE%-%BUILD_CRT%-Build
#    type: zip
